### ISSUE TITLE
Theming support

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#203]
Most importantly, respect `prefers-color-scheme` with a corresponding dark theme.
And the option to package everything onto the server and not depend on a CDN like Cloudflare.

**Comment by mikebarkmin** [comment]
A dark theme would a nice. I will see what I can do ;)

I will also try to integrate KaTeX and HighlightJS or provide a configuration option for pointing to the resources.

**Comment by mikebarkmin** [comment]
I have integrated KaTeX and removed every use of a CDN: 533303a4430b69d8d56d8c0aaf9b3640d1f51f3f

I also created a dark theme, which is used when the user has a dark system setting: 6f2728ea24596f840868f19fd761bfdf9eee7b10

**Comment by mikebarkmin** [comment]
You only have to call `npx hyperbook setup` and the new template will be downloaded. In the future you might be notified, if the template has been updated.

**Comment by mikebarkmin** [comment]
Ich habe es für eure Dokumentation ausprobiert und finde, dass es ganz gut aussieht. Falls was mit dem dunklen Design nicht stimmt, schicke mir bitte einen Screenshot und ich werde versuchen das zu korrigieren. :)

**Comment by FalconsSky** [comment]
Vielen Dank! :)

**Comment by xeruf** [comment]
Danke! Wenn ich auf dem offiziellem https://hyperbook.openpatch.org gucke, erscheint es mir lediglich etwas kontrastarm.
