### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by FalconsSky** [openpatch/hyperbook#208]
We have in our documentation the case that we have sometimes quite long pages with several sections, which can be divided semantically badly into several MDs.
Accordingly, it would be quite practical if you can include a TOE in the page, which is generated automatically.

**Comment by mikebarkmin** [comment]
I thing that this is a great idea. I will probably implement a TOC on the right-hand-side, which will move into a slideout menu on mobile, similar to the main navigation, but only on the other side.

I will probably add a page configuration option to disable the TOC for pages, but I will probably enable it per default for all pages. For the glossary I will probably disable it by default.
