### ISSUE TITLE
Link to heading in glossary

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#209]
We have some rather extensive glossary entries, so we would like to link to a page such as:

    /glossary/contest#computerspieler
    
Now of course I can link to this: `[Wettkampfsystem>Computerspieler](/glossary/contest#computerspieler)`
but I think `:t[Wettkampfsystem>Computerspieler]{#contest#computerspieler}` would be more elegant.

Or maybe we are misusing the glossary and the content should actually be on an own page linked from the glossary entry,
let me know what you thnk :)

**Comment by mikebarkmin** [comment]
I personally though of the glossary as a list of definitions, so shorter texts. But I see your use-case.

I think the term directive should be extended to:
`:t[A Term]{#term anchor="heading2"}`

**Comment by xeruf** [comment]
hm, that seems like unnecessary new syntax. Why not remove the hashtag from the glossary term and simply do it like this?

     :t[A Term]{term#heading2}

**Comment by mikebarkmin** [comment]
Because I decided to extend markdown with directives: https://github.com/remarkjs/remark-directive

:t is short for term. But maybe :g would be better.

**Comment by mikebarkmin** [comment]
I have implemented it in 7e95234c0b859314e0fd38521e238088e5e7ba1c and documented it here: https://hyperbook.openpatch.org/elements/glossary
