### ISSUE TITLE
Make Bookmarking more intuitive

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#211]
Some Tools have this little link-chain-symbol to the right of the text,
so I often click the bookmark button to copy the section link and get confused,
especially because _nothing_ happens when I click that button.

**Comment by mikebarkmin** [comment]
I used Github as a reference for the chain icon. They also have it on the left-hand-side. But I could implement a little toast notification for adding and removing bookmarks. Which tools have it on the right-hand-side?

**Comment by xeruf** [comment]
I don't know at the moment, and I don't suggest you move it, simply provide feedback when using the bookmark - maybe something like an emanating fading circle at the cursor if you know what I mean.

Another small issue here is that the chain itself is not clickable.

**Comment by mikebarkmin** [comment]
I made the link icon clickable and added a tooltip to the bookmark icon. Even though did not want to do that, because now there is something which might need translations in the future, but it should help for clarity.
