### ISSUE TITLE
Make it work without basepath

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#212]
When I try to open the built files locally, or on a server on a subpath, the `_next` folder fails to load. Yes I can set the `basePath` in the book configuration, but it should be possible without it so the hyperbook is portable.

**Comment by mikebarkmin** [comment]
Since hyperbook uses nextjs under the hood, I am not sure how I would implement this. Their documentation also does not provide a adaptive setting for the basepath https://nextjs.org/docs/api-reference/next.config.js/basepath. If you have an idea for how implemented it please let me now.

**Comment by xeruf** [comment]
my idea was to use relative include paths instead of absolute ones so the application does not have to mind, idk if that works in nextjs though

**Comment by mikebarkmin** [comment]
I think that this is not how nextjs works, therefore I will close this one until nextjs supports it.
