### ISSUE TITLE
Cut off pages on mobile devices

### ISSUE THREAD

**Issue by FalconsSky** [openpatch/hyperbook#214]
We have now taken [our documentation](https://docs.software-challenge.de/) live with Hyperbook. 
We noticed afterwards that on mobile devices, with small displays, not all the space is used:
![image](https://user-images.githubusercontent.com/35808469/185742716-a13ab389-e41a-43ff-b13d-32899e4c2824.png)
Furthermore, the Safari browser on iOS seems to cut off a few pages and it is not possible to scroll sideways:
![image](https://user-images.githubusercontent.com/35808469/185742789-9fa85079-bdae-4544-a17e-e89fb08b298a.png)
On the other hand, things are looking good on other sites:
![image](https://user-images.githubusercontent.com/35808469/185742812-c3540d19-0948-4b61-ab5e-016e57815140.png)

**Comment by mikebarkmin** [comment]
I will investigate the issue and can hopefully provide a solution till monday.

**Comment by mikebarkmin** [comment]
It should be fixed now.

**Comment by FalconsSky** [comment]
Thanks!
