### ISSUE TITLE
Opening a glossary page directly produces an empty page and a 404

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#215]
I still had this open in my browser, and it was rather confusing to be greeted by a blank page, regardless of reloads or incognito mode.
Only navigating back and forth manually could fix it.

![image](https://user-images.githubusercontent.com/13354331/185746216-09bca2ca-8f0e-47c3-9fdf-46c5326b1447.png)

**Comment by mikebarkmin** [comment]
Interesting it does not happen on hyperbook.ooenpath.org at least for me. https://hyperbook.openpatch.org/glossary/oop

**Comment by FalconsSky** [comment]
I had the problem myself when testing Hyperbook with nginx.
My solution was to tell nginx to always start from the index to see if the page exists:
```
server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}
```
[Source](https://stackoverflow.com/a/56214426)

**Comment by mikebarkmin** [comment]
Here is how you can configure nginx with nextjs and therefore hyperbook https://gist.github.com/jjsquady/5399d6e1b23f501083a9c262d806e248

**Comment by xeruf** [comment]
@mikebarkmin so you use such a config, too?
Anyways, we use Caddy, what about that?

**Comment by xeruf** [comment]
Alternatively: https://docs.software-challenge.de/allgemein/spiel.html works while https://docs.software-challenge.de/allgemein/spiel does not, so if the navigation menu entries would simply link to the `.html`, it would work fine without any special config :)

**Comment by mikebarkmin** [comment]
I host the documentation for hyperbook on Vercel, but I also have an example for GitHub pages. These work fine. See: https://www.barkmin.eu/hyperbook-github-pages/glossary/hyperbook

I think you should add this to your Caddyfile

```
try_files {path}.html {path}
```
See: https://caddyserver.com/docs/v2-upgrade#ext

**Comment by mikebarkmin** [comment]
I accidentally closed the issue. Did this solve your problem?

**Comment by xeruf** [comment]
Thanks, fixed it :)
