### ISSUE TITLE
Codeblock font color too dark in darkmode

### ISSUE THREAD

**Issue by jnccd** [openpatch/hyperbook#217]
![image](https://user-images.githubusercontent.com/19777592/185755863-30de0c5d-55bc-41a1-8b4d-9fe5fb2910d7.png)
![image](https://user-images.githubusercontent.com/19777592/185756125-fb17aefd-1f5e-405d-9bb1-82979e42c041.png)

Low font/background contrast makes it hard to read the XML code here.
A somewhat lighter text font color would be nice.

**Comment by mikebarkmin** [comment]
There was an issue with the standard highlightjs css overwritting the wanted one. I fixed it in 1671b3534155990ccea980a6fe84b600b8598737
