### ISSUE TITLE
TOC Button Alignment

### ISSUE THREAD

**Issue by FalconsSky** [openpatch/hyperbook#220]
I noticed that in the Edge browser the TOC button is above the scroll bar. This problem only seems to exist in browsers that have this large bar.
Edge-Chromium:
![image](https://user-images.githubusercontent.com/35808469/185782809-da298432-0b83-43de-a1bd-f71565440c46.png)
Firefox:
![image](https://user-images.githubusercontent.com/35808469/185782893-4796fcee-8b83-4d76-a623-44dd0c440786.png)

**Comment by mikebarkmin** [comment]
Ok. I will move it a bit to the left.
