### ISSUE TITLE
Protect areas with a password

### ISSUE THREAD

**Issue by mikebarkmin** [openpatch/hyperbook#23]
Example Application:

```md
:::protect{password="Super Strong", description="Solve Task 1 to get the password!"}
I am protected.
:::
```

The password should be saved in LocalStorage or in SessionStorage.

- LocalStorage would save the password even after a browser restart
- SessionStorage would only keep the password until the page is closed

If we opt in for LocalStorage there should be a mechanism to clear all passwords.

**Comment by mikebarkmin** [comment]
Solved in 49fcaa73ef2edc268ba5984e0fae4fc7cf4ebed4

**Comment by xeruf** [comment]
Markup here is not accurate: no comma, and it needs an empty line between the content and the lines with `:::` - just for documentation ;)

See https://hyperbook.openpatch.org/elements/protect

**Comment by mikebarkmin** [comment]
Thanks, I edited my comment.
