### ISSUE TITLE
Glossary backlinks redundant commas

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#238]
For example at https://docs.software-challenge.de/glossary/xml

![image](https://user-images.githubusercontent.com/13354331/185742096-0c425b54-4d7b-4263-85ba-3da0052b010a.png)

I guess this happens because there are multiple links from some pages. Could also be that the pages are missing a title or something and are usually hidden.

**Comment by mikebarkmin** [comment]
I think this has happened, because some pages do not have a name property in the yaml frontmatter. I now exclude pages, which are hidden and which do not have a name from being listed.
