### ISSUE TITLE
Support for other fonts

### ISSUE THREAD

**Issue by FalconsSky** [openpatch/hyperbook#261]
It would be great if you could define in `hyperbook.json` which font you want to use.
Something like:
```json
"font": "Inter"
````

**Comment by mikebarkmin** [comment]
This is a great idea. The only problem I am currently thinking about is, where does the font come from? Maybe the configuration should allow for defining a path to a font file like this:

```
"fontSrc": "/inter.woff"
```

This font file then needs to be present in the public directory. This would also allow for remote fonts, like this:

```
"fontSrc": "https://another-server.de/font.woff"
```

I am also thinking of splitting the fonts for headings and texts. So my proposal would look like this:

```
"font": {
  "heading": "/inter.woff",
  "text": "/montserrat.woff"
}
```

and if you want to use the same font for both, you could just define it like this:

```
"font": "/inter.woff"
```

What do you think of this?

**Comment by FalconsSky** [comment]
> `"code": "/fira-code.woff"`

I didn't even think about the code blocks.
I think your idea with separating the title, code blocks and body text makes a lot of sense.

That you put the font then in the folder, or a link, sounds good.

*I also thought that some fonts would be pre-installed. But I don't know enough about Next JS I guess. 😄*

**Comment by mikebarkmin** [comment]
There are no preinstalled fonts. Currently, I am using `sans-serif` as a font. This currently means different fonts for different os / browser (see: https://fontsarena.com/blog/operating-systems-default-sans-serif-fonts/). This means faster loading times, since no font-file has to be loaded. But I understand the desire to customize the font, and it is oped-in, so I am happy to implement it. :)

**Comment by FalconsSky** [comment]
Thank you very much!

**Comment by mikebarkmin** [comment]
Done :) The documentation now uses Montserrat and FiraCode for an example. https://github.com/openpatch/hyperbook/blob/main/website/hyperbook.json
