### ISSUE TITLE
Custom fonts are not affecting titles

### ISSUE THREAD

**Issue by FalconsSky** [openpatch/hyperbook#264]
Regarding Issue #261 .
If I add the fonts to `hyperbook.json` and put them in the public folder, the titles are not adjusted accordingly.
Is `heading` only meant for the top section where the logo can be found, or should this also affect all other titles?

**Comment by mikebarkmin** [comment]
It should affect every heading. Let me take a look.

**Comment by mikebarkmin** [comment]
It is fixed. I was confused by my naming and use title instead of heading in the css. Now everything should look fine :)
