### ISSUE TITLE
Add blog

### ISSUE THREAD

**Issue by mikebarkmin** [openpatch/hyperbook#325]
For reporting on the changes and new features of hyperbook a blog would be a welcomed addition. Just like the glossary, would probably would create a new folder `blog` and reserve the pages `/blog` and `/blog/*`. Every page in the blog folder also should get two new properties `image`, `abstract` and `date`. The image and abstract should be used for displaying all blog pages on the `/blog` page. If no abstract is defined, the first 200 character should be used as one. The date should be used for ordering the blog pages.

**Comment by xeruf** [comment]
Consider taking inspiration from https://github.com/novoid/lazyblorg which I am now setting up my blog with ;)

**Comment by mikebarkmin** [comment]
This should be possible with the new pagelist element. In combination with a hidden section and using the date in the filename. For example, consider the following directory structure 

- /book/blog-content/2024-07-24-nice-article.MD
- /book/blog-content/2024-07-24-nice-article.MD
- /book/blog-content/index.md

The index.md should be hidden. 
```md
---
hide: true
---
```

Then you need to add a index to your blog:

/book/book.md

```md
::pagelist{format="ul" source="href(/blog-content/.*)"} 
```

This should give you a basic blog.
