### ISSUE TITLE
Consider Orgdown / Org-Mode as Markdown alternative

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#346]
Most of the syntax extensions that seem foreign in markdown could be natively supported in org: https://orgmode.org/manual/Blocks.html#Blocks

See a motivational post at https://karl-voit.at/2017/09/23/orgmode-as-markup-only/

More material later if needed :)

**Comment by mikebarkmin** [comment]
If I am understand correctly something like this:

```md
::::tabs{id="my-tabs"}

:::tab{title="Hi"}

A Tab

:::

::::
```

you look like this in org-mode:

```org
#+BEGIN_TABS :id my-tabs

#+BEGIN_TAB :title Hi

A Tab

#+END_TAB

#+END_TABS
```

**Comment by mikebarkmin** [comment]
The question is not whether the extended syntax does look foreign to Markdown, it is rather if the extended syntax is easily readable by a non-it person. Since one major target group of mine are teachers. I like that in the org mode syntax, the blocks end with context. In my extended markdown, you lose the context, which probably makes it harder to reason about.

**Comment by mikebarkmin** [comment]
I am also not sure how easy it would be to implement custom block in org-mode and what a good org-mode parser for JavaScript is. Currently, I am using remark with this plugin https://github.com/remarkjs/remark-directive, which also works with React components, which makes it super-easy to develop with.

**Comment by xeruf** [comment]
yes, the ecosystem for orgdown/org-mode is still a bit young outside of emacs, but I think it is worth promoting because org has standards and integrations which provide a lot of flexibility - and as outlined in the article, it is more consistent and easy to write than markdown in its simplest form.
Here is a list of tool support: https://gitlab.com/publicvoit/orgdown/-/blob/master/doc/Tool-Support.org

**Comment by mikebarkmin** [comment]
I am also looking for ways to enable non tech-savvy people to use hyperbook. Currently gitpod.io or VS Codium with the extension is probably the best. Hedgedoc does look nice though :)

**Comment by xeruf** [comment]
> I am also not sure how easy it would be to implement custom block in org-mode

In org-mode you can always add custom blocks and they will be foldable at least in editors, even if they might not know what to do with them:
https://orgmode.org/manual/Blocks.html

So just like with markdown, the actual implementation of the custom block would be in the converter.

Have you dropped this idea fully now?
