### ISSUE TITLE
Weird list spacing

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#347]
Look at the compiled output of:
```md
- test1
- test2
- test3
- test4
```
vs
```md
- test1
- test2

- test3
- test4
```

For some reason, the second example adds spacing everywhere rather than only between the lines that are actually spaced apart.

**Comment by mikebarkmin** [comment]
Even though I find it strange, I think it is the expected behavior of Markdown. See:

- test1
- test2
- test3
- test4

test

- test1
- test2

- test3
- test4

**Comment by xeruf** [comment]
do we have to follow that though?
I don't think any spec says that it has to be like that, and I cannot envision a usecase for the below, but multiple use-cases where I would like to have multiple bullet lists with spacing in between.

**Comment by mikebarkmin** [comment]
I think it is specified here: https://daringfireball.net/projects/markdown/syntax#list

**Comment by mikebarkmin** [comment]
Or this specificaton of commonmark: https://spec.commonmark.org/0.30/#example-306

**Comment by mikebarkmin** [comment]
The provided solution in the specification is to do this:

```
- test
- test

<!-- -->

- test
- test 
```

- test
- test



- test
- test

**Comment by xeruf** [comment]
ah okay, but it says:
> There can be any number of blank lines between items:

I don't see a mention that that would raise the spacing of all list items?
