### ISSUE TITLE
Repeated protect blocks

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#348]
I have protect blocks with the same password and description spread throughout the book pages to hide internal content for non-internals, maybe we can find some way to prevent repetition in that case?

**Comment by mikebarkmin** [comment]
That is an interessting scenario, since I also ran into this issue. But I am not sure how to solve it, do you habe a suggestion?

**Comment by mikebarkmin** [comment]
What do you think about something like a snippets folder? Each file in a snippets folder is just a markdown file. The snippet aka the content of the markdown file could then be used in a page like this:

```
:snippet{#protect-internal}
```

**Comment by mikebarkmin** [comment]
Maybe one could also add arbitrary properties, which could be used in the snippet.

```
:snippet{#protect-internal hint=false}
``` 

```
::protect{password="my-password"}

{{#if hint}}
::alert{info}

A hint

::
{{/if}}
```

The snippets would probably be written in the [handlebar syntax](https://handlebarsjs.com).

**Comment by xeruf** [comment]
that sounds nifty!

**Comment by mikebarkmin** [comment]
Here you go https://hyperbook.openpatch.org/elements/snippets Have fun :smile:
