### ISSUE TITLE
Option to unprotect in development mode

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#361]
When editing and previewing protect blocks, I often comment them out to see what I am doing.
Would be nice to have an option to automatically unlock them only in dev mode.

**Comment by xeruf** [comment]
Thank you, you are awesome!
But it's not quite what I want I think - when I edit and the browser hot-reloads, I want it to be immediately visible without any further interaction - that's why I think it should be a config :)

**Comment by mikebarkmin** [comment]
OK, I got it. I think a separate `hyperbook.dev.json` would be good for setting stuff only in development. I think it should be similarly structured to the `hyperbook.json`, so you can overwrite properties.

```json
{
   "elements": {
      "protect": {
          "reveal": true
      },
     "bookmarks": false,
   }
}
```
