### ISSUE TITLE
title tags not working

### ISSUE THREAD

**Issue by FalconsSky** [openpatch/hyperbook#427]
The tags that are appended at the end of a url seems not to work properly.
e.g.:
https://docs.software-challenge.de/allgemein/wettkampf#die-begegnungen
https://docs.software-challenge.de/spiele/penguins/regeln#wertung

**Comment by mikebarkmin** [comment]
Thanks. I think I know what is causing the bug. The markdown is loaded after the anchor tag is search. I will try to implement a fix.

**Comment by mikebarkmin** [comment]
I think I found a solution d92c89e099476c0b941ed9fea83ca75fd24c034d
