### ISSUE TITLE
search function

### ISSUE THREAD

**Issue by maxblan** [openpatch/hyperbook#428]
A search bar, which is available throughout the documentation, could be very helpful if you are looking for a keyword but don't know where to click through.

**Comment by mikebarkmin** [comment]
I think this is very useful. I am currently not sure what to index of a given page. Only the keywords in the frontmatter, the full-text, just the headings?

At the moment, this library is my favorite for implementing this feature: https://github.com/nextapps-de/flexsearch

**Comment by FalconsSky** [comment]
I think a search bar that searches the entire text makes the most sense.

**Comment by mikebarkmin** [comment]
And the search unit should probably be a section? Or is a page enough?

**Comment by FalconsSky** [comment]
I was thinking more of the search bar searching all the documentation no matter where you are and then just taking you there and maybe highlighting that keyword.

**Comment by mikebarkmin** [comment]
This will be included in the next release.
