### ISSUE TITLE
Turn page button

### ISSUE THREAD

**Issue by FalconsSky** [openpatch/hyperbook#449]
Normally there is a button at the end of each page that allows you to scroll to the next page. However, this is a bit buggy in the glossary. I assume that these buttons are not supposed to appear there?
e.g.: https://docs.software-challenge.de/glossary/player#der-fortgeschrittene-spieler
![image](https://user-images.githubusercontent.com/35808469/202145304-767cbbdd-b284-4875-8b28-3fda7c310d47.png)

**Comment by mikebarkmin** [comment]
The Links show all pages, which contain the term. But you are right, that the links are broken. I will look into it.

**Comment by mikebarkmin** [comment]
Fixed in f906c5075ec26263f90fabfa2a8ad556619c86da
