### ISSUE TITLE
Possibility to change the font size

### ISSUE THREAD

**Issue by maxblan** [openpatch/hyperbook#450]
It is now possible to change the font itself. One problem I have noticed is that fonts can vary in size and thickness in their standard form.
Therefore, I think that a possibility to change the size of the individual headings and bodies, so that the font can be adjusted better, would be great.

**Comment by mikebarkmin** [comment]
I agree. I will see if I can make this happen. I probably have to rework some css to use relative units for this to work.

**Comment by mikebarkmin** [comment]
I think size-adjust would be perfect for this use-case. Unfortunately, it is not support on safari.

https://web.dev/css-size-adjust/

I am looking for other possibilites.

**Comment by FalconsSky** [comment]
How about changing the `x-height` of the font for instance with [`opentype.js`](https://github.com/opentypejs/opentype.js). Shouldn't the fonts then adapt quite well?
The lib is more for editing of fonts than reading their props, but maybe that would be a solution.

**Comment by mikebarkmin** [comment]
Implemented in 8da55e5d20f8b924e016b60ff36c461f7be1e2c2
