### ISSUE TITLE
Link line break

### ISSUE THREAD

**Issue by FalconsSky** [openpatch/hyperbook#451]
We have the problem in several places in our documentation that words containing a link are interrupted in the middle of the word when the linebreak is reached and continue on the next line.
![image](https://user-images.githubusercontent.com/35808469/202147740-be19d809-b2e9-40e8-be4c-5b4f84e13064.png)
I think that it is rather intentional that the whole word only starts in the next line?

**Comment by mikebarkmin** [comment]
Sorry. I wanted to deal with long urls which did not break. I missed that this would also have an influnce on normal text. I will revert the changes and keep searching on how to deal with long links.
