### ISSUE TITLE
Bitflow Documentation

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#520]
I wanted to add a Bitflow assessment to my Hyperbook, but the documentation is missing on all parts which would enable me to create one, even the examples, which could help me to infer the structure, are empty.

I think the Hyperbook documentation about Flow should also link to https://bitflow.openpatch.org/docs/flow

And woulnd't it be sensible to have the bitflow docs generated via hyperbook as well? ;)

**Comment by mikebarkmin** [comment]
Both is true. In a perfect world, I would have gotten around to extend the Bitflow-Online-Editor. So you could just use it and export a .bitflow file. But I need to find time to do that.

**Comment by xeruf** [comment]
Well, posting an example json from somewhere you already use it or a link to it would already help a lot ;)

**Comment by mikebarkmin** [comment]
https://github.com/openpatch/hyperbook/blob/main/website/de/public/task.json

**Comment by xeruf** [comment]
was bitflow removed entirely? can't find it in the docs anymore

**Comment by mikebarkmin** [comment]
Yes, I have removed it. You need to stay on version 0.33.3, if you want to use it now.
