### ISSUE TITLE
Option for an edit/contribute link per page

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#521]
Like on read the docs, for example on https://zulip.readthedocs.io there is a "Edit on Github" link on the top right.
For that, the repo url needs to be configured appropriately. 
I would suggest adding a single config option, something like "editPrefix", and if it is set, show such a link in the footer.

This value should be something like this for this repo: `https://github.com/openpatch/hyperbook/edit/main/website`

**Comment by mikebarkmin** [comment]
I do not understand the issue. There is currentently a Edit on Github Link in the footer of a page, when the repo property is set in the hyperbook.json file.

**Comment by mikebarkmin** [comment]
like on the hyperbook documentation website.

**Comment by xeruf** [comment]
Oh I missed that - but it only seems to work for github links so far :/

**Comment by mikebarkmin** [comment]
This sounds reasonable.

**Comment by mikebarkmin** [comment]
It is implemented. https://hyperbook.openpatch.org/configuration/book See under repo.
