### ISSUE TITLE
Real life examples?

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#59]
Looks great, but are there any live examples online?

**Comment by mikebarkmin** [comment]
https://hyperbook.openpatch.org/ is written with hyperbook. I am also currently working on a workbook for developing a Smart Lights System with Raspberry Pis, Adafruit Huzzahs and the MIT App Inventor. The workbook will be based on this repository: https://github.com/mikebarkmin/smartlights.

**Comment by xeruf** [comment]
sure, the documentation, but I was wondering how it looks in an actual use-case - so that's not ready yet, then. I'll keep an eye on this project though :)

**Comment by xeruf** [comment]
Now powering https://docs.software-challenge.de and we are eager to build some IT quizzes with it, too :)
