### ISSUE TITLE
support more headline levels

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#617]
following up to https://github.com/openpatch/hyperbook/issues/613, level 4 is barely distinguishable from level 3, and everything below seems to be the exact same.
Maybe with the new version this will be less relevant, but still something to note.

**Comment by mikebarkmin** [comment]
Can you please check, if it is now better: https://hyperbook.openpatch.org/markdown/header

**Comment by xeruf** [comment]
Looking good, any particular reason why H2 is underlined but not H1?

**Comment by mikebarkmin** [comment]
my thought was that you probably only have one h1 the page title and then many h2 which are the main sections. Github underlines h1 and h2. What is your preferred style?

**Comment by xeruf** [comment]
if that is the suggested layout, maybe write it somewhere - I was still figuring it out, sometimes I omitted the page title altogether and created multiple h1 sections.
Example without page title, where I now moved all sections down by one: https://about.ftt.gmbh/projects/ideas
