### ISSUE TITLE
Static header link names

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#627]
The name of a section can change, but if I link to the hyperbook, I would like the link to stay consistent. Maybe an option to add a reference alias to a header, like the heading id in org-mode?

**Comment by mikebarkmin** [comment]
I encountered the same problem. I think mamy markdown engine support custom ids
like so: 

    ### My Great Heading {#custom-id}

I am going to implement it the next days.

**Comment by mikebarkmin** [comment]
Implemented in 764a681e4a8b0135ffa83f0a30c4cda23b79babd

**Comment by xeruf** [comment]
thank you - all of these are native in org-mode/orgdown, we should really consider the switch :)
