### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#837]
If hyperbook ever introduces breaking changes, old books will be irreversibly broken because repos don't track the used hyperbook version with `npx`. Any way to remedy that? `npx` is cool but maybe not ideal for stability?

**Comment by mikebarkmin** [comment]
You can install a certain hyperbook version by using `npx hyperbook@0.24.1`.

**Comment by xeruf** [comment]
This does not address my concern, as the used version is still not tracked within the `package.json` or the like.
