### ISSUE TITLE
Build fails on Windows using SC repo

### ISSUE THREAD

**Issue by jnccd** [openpatch/hyperbook#838]
When following the readme here: https://github.com/software-challenge/docs, I get the following error on Windows
![image](https://github.com/openpatch/hyperbook/assets/19777592/5bb3815b-8ce4-4885-af0e-e03a843098d4)
Due to the stacktrace this looks like a package issue, is there official Windows support?

**Comment by mikebarkmin** [comment]
I will take a look at it later today. I have tried to use os independet apis, but I only test hyperbook on Linux. I will try using it in a VM and will report, if I can fix this error.

**Comment by mikebarkmin** [comment]
The issue will be resolved in the next version of hyperbook. But I would suggest looking into the VS Code extensions. It will make writing hyperbook so much faster ;) 

https://marketplace.visualstudio.com/items?itemName=openpatch.hyperbook-studio

I wil need to update the screenshot on the marketplace page, but I will be a full preview of your hyperbook.

**Comment by jnccd** [comment]
I'll try that
Thank you so much for your work 🙏

**Comment by mikebarkmin** [comment]
You could also use the Linux Subsystem for Window. This makes it much easier for developers on Windows ;)
