### ISSUE TITLE
Do not assume webserver config

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#846]
In https://github.com/openpatch/hyperbook/issues/215 we had the issue already:
The webserver config has to implicitly add the .html suffix to any requested site, which makes for nice URLs but requires custom webserver configuration. Can we have an option for it to work with a standard file-serving webserver?

**Comment by mikebarkmin** [comment]
I'm trying to investigate possible solutions to the problem.

One solution might be to use directories with index.html for every page. This would be an easy implementation.

```
├── elements
│   ├── alert
│   │   └── index.html
│   ├── archive
│   │   └── index.html
│   ├── audio
│   │   └── index.html
│   ├── bitflow
│   │   └── index.html
│   ├── bookmarks
│   │   └── index.html
│   ├── collapsible
│   │   └── index.html
│   ├── download
│   │   └── index.html
│   ├── embed
│   │   └── index.html
│   ├── emoji
│   │   └── index.html

```

Add an html extension to every internal link is another solution, but I am currently not sure in which places I have to make changes. So I have to look into it further.

**Comment by mikebarkmin** [comment]
Implemented in bd83e3a1a2bc49a6509dbdc15e085642100a55ff

**Comment by xeruf** [comment]
just fyi, using HestiaCP I was able to configure apache2 to work with the old version through adding `Options +MultiViews`: https://httpd.apache.org/docs/current/content-negotiation.html#negotiation

**Comment by xeruf** [comment]
was this reverted? getting files again

**Comment by mikebarkmin** [comment]
Yes, I have removed it. You need to stay on version 0.33.3 to use it.

**Comment by mikebarkmin** [comment]
In v0.46.0 it is back again. Sorry, I missed this option, when I rewrote everything.
