### ISSUE TITLE
Snippet arguments with whitespace do not work

### ISSUE THREAD

**Issue by jneug** [openpatch/hyperbook#853]
I'm having problems using snippet parameters containing whitespace characters.

## Example
`snippets/whitespace.md.hbs`:

```hbs
"{{{title}}}"
```

`book/whitespace-test.md`:

```md
:snippet{#whitespace title="My Title"}
```

will compile to 

```html
""
```

while 

```md
:snippet{#whitespace title="My_Title"}
```

gives 

```html
"My_Title"
```

**Comment by jneug** [comment]
As a workaround, the `replaceAll` function can be used:

```hbs
"{{replaceAll title "_" " "}}"
```

```md
:snippet{#whitespace title="My_Title"}
```

**Comment by mikebarkmin** [comment]
Thanks for the report. I will look into it.
