### ISSUE TITLE
Add custom CSS-file option

### ISSUE THREAD

**Issue by jneug** [openpatch/hyperbook#856]
I propose to add a "styles" key to the `hyperbook.js`, that takes a filename from the `public` directory and adds it as a stylesheet to the Hyperbook.

```json
{
  "name": "Hyperbook",
  "version": "0.0.1",
  "description": "My Hyperbook",
  "license": "CC-BY-SA",

  "logo": "logo.png",
  "styles": "styles.css"
}
```

This would allow users to customize the color scheme in general and specifically would be a good addition to support custom HTML elements in #854.

**Comment by mikebarkmin** [comment]
In the next release you will be able to define custom styles and scripts either in the hyperbook.json to use the in all pages. Or in the frontmatter of a page to only include them in this page.
