### ISSUE TITLE
Add next/prev keys to page frontmatter

### ISSUE THREAD

**Issue by jneug** [openpatch/hyperbook#859]
I propose two new keys for page frontmatter that allow the modification of link targets for the navigation buttons on the bottom of pages. 

Currently, the links navigate to the next page according to the `index` key. This is sensible, but there are cases where one might want to navigate to other pages in the book.

Setting the keys to an empty string would hide the buttons from a page. 

For example this frontmatter in `last-page.md` would show a "previous" button to `previous-page.md` and no "next" button. 
```md
---
title: Last page in path
next: 
prev: previous-page
---
```

**Comment by mikebarkmin** [comment]
Implemented in 90c99bd
