### ISSUE TITLE
Odd <wbr> tags

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#875]
In recent weeks this odd tag creeped in, and I think it might be an issue in the generation logic? See https://docs.software-challenge.de/ source repository is linked in there.

![image](https://github.com/openpatch/hyperbook/assets/13354331/001a5450-5c7c-4038-8af3-567b6f6dd7b8)

**Comment by mikebarkmin** [comment]
I will take a look. Wbr Tags normaly indicate to the browser where a wordbreak is OK. But they should not be visible like this.

**Comment by mikebarkmin** [comment]
Fixed in #876
