### ISSUE TITLE
Snippets detection not strict enough

### ISSUE THREAD

**Issue by jneug** [openpatch/hyperbook#887]
It appears that snippets are sometimes scanned past their terminating bracket. I have a `wikipedia` snippet like this:

```hbs
[{{#if titel}}{{titel}}{{^}}{{seite}}{{/if}}](https://de.wikipedia.org/{{seite}})
```

I have the following paragraph:
```md
Du kannst das Programm am schnellsten per 
:snippet{#wikipedia seite="Kopieren_und_Einfügen" titel="Kopieren und Einfügen"} 
in den Editor übernehmen. Du musst aber aufpassen: Wie du weißt 
sind die Einrückungen (Leer- und :snippet{#wikipedia seite="Tabulatorzeichen"}) 
in Python Teil des Programms .
```

resulting in this output:

```html
Du kannst das Programm am schnellsten per <a href="https://de.wikipedia.org/Tabulatorzeichen">Kopieren und Einfügen</a> ) in Python Teil des Programms
```

**Comment by jneug** [comment]
From having a quick look at the regex, I assume you could fix it by making the second to last quantifier non-greedy (maybe the one before that, too):

From 

```regex
((:+)snippet{#(?<snippet>[a-zA-Z0-9-]+)(?<vars>( +(?<var>[a-zA-Z]+)=(?<value>\d+|false|true|".*"))*) *})
```

to

```regex
((:+)snippet{#(?<snippet>[a-zA-Z0-9-]+)(?<vars>( +(?<var>[a-zA-Z]+)=(?<value>\d+|false|true|".*?"))*?) *})
```

**Comment by mikebarkmin** [comment]
I tested your idea, but unfortunately, it did not solve the issue. I also tested the regex with regexr, and it seems to work ok.

regexr.com/882ni

**Comment by jneug** [comment]
It only happens if the newlines are removed from the example paragraph. Then the original regex will be too greedy.

Making the quantifier in quotes not greedy should solve it:
```regex
((:+)snippet{#(?<snippet>[a-zA-Z0-9-]+)(?<vars>( +(?<var>[a-zA-Z]+)=(?<value>\d+|false|true|".*?"))*) *})
```

**Comment by mikebarkmin** [comment]
It seems like it is working. Here is a demo repo: https://github.com/mikebarkmin/hyperbook-snippets-test
