### ISSUE TITLE
Directives in pagelist snippets 

### ISSUE THREAD

**Issue by jneug** [openpatch/hyperbook#905]
I tried to build a portal page by using `pagelist` with a snippet that creates `tiles` from the pages. It seems like directives in snippets used by `pagelist` are not parsed. Is this intentional?

Example snippet in `portal.md.hbs`:
```handlebars
:::tiles

{{#each pages}}
::tile{title="{{{ name }}}" href="{{ href }}"}
{{/each}}

:::
```

Example call to `pagelist`:
```
::pagelist{format="#portal" source="href(/EF/*) AND keyword(lernpfad)" orderBy="index"}
```

**Comment by mikebarkmin** [comment]
No, this is not intended. Thanks for reporting the bug. It should be fixed in the next version. See [2ab94ae](https://github.com/openpatch/hyperbook/commit/2ab94aea525c2b67c156313f13d9662efad5d8a6)

**Comment by jneug** [comment]
Great. Thanks for the quick responses. Makes porting my Wiki to Hyperbook much more convenient.
