### ISSUE TITLE
Virtual Folders broken since update 

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#913]
See https://docs.software-challenge.de/spiele/25_hase-und-igel/xml

"Spiele" should not be visible as per https://github.com/openpatch/hyperbook/issues/205 but seems the latest rewrite somehow broke that feature :/

**Comment by mikebarkmin** [comment]
Sorry. It was a little logic error, which is fixed in 0.38.3

**Comment by xeruf** [comment]
now the virtual section is gone completely in the sidebar :eyes: https://docs.software-challenge.de/spiele/25_hase-und-igel/xml

**Comment by xeruf** [comment]
temporarily disabled virtual because of that

**Comment by mikebarkmin** [comment]
Fixed in #915

**Comment by xeruf** [comment]
thanks, working again :)
